#!/bin/bash

order=( "2d-geometry*.md" "3d-geometry*.md" "inverse-kinematics*.md" "2d-velocity-kinematics*.md" )

rm -f combined.md

for i in "${order[@]}"
do
  # Add in title of each section. Get first file name, remove dash, and capatilise.
  (echo $i | sed -r 's/-...md(.*)//' | sed 's/-/ /g'| sed 's/\<./\U&/g' | sed -r 's/(^.)d/\1D/' | sed -r 's/^(.*)/\n# &/') >> combined.md
  for f in $i
  do
    # Convert yaml title to # and add a seperater after each file
    # Also change all headings down a level so section titles can be h1
    (echo "" ; echo "---" ; echo ""; cat $f | sed 's/---//g' | sed -r "s/title: '(.*)'$/# \1/" | sed -r 's/^#/##/') >> combined.md
  done
done
